# Identificador unico del proyecto
sonar.projectKey=PHP01
# Nombre que se vera en el panel de SONARQUBE
sonar.projectName=PHP01
#Archivos que analizara,,, el "." significa esta carpeta
sonar.sources=.
# Carpetas a excluir del análisis 
sonar.exclusions=vendor/**, node_modules/**, public/**, storage/**
